"use client";

import { useState } from "react";

const AddJobForm = () => {
  const [position, setPosition] = useState("");
  const [experience, setExperience] = useState("");
  const [skills, setSkills] = useState("");
  const [description, setDescription] = useState("");
  const [aiDescription, setAIDescription] = useState("");

  // Demo action: replace with API or logic
  const handleGenerateJD = () => {
    setAIDescription(
      `Job Description for ${position || "the given role"} generated by AI...`
    );
  };

  return (
    <>
    <div className="min-h-screen bg-white flex flex-col items-center px-4 pt-12">
    <a
        href="/joblistings"
        className="text-black underline font-medium self-start mb-4"
    >
        ⬅️ Back to Job Listings
    </a>
      <div className="flex justify-between items-center mb-8">
        <h1 className="text-2xl font-bold mb-8">Add a New Position</h1>
        </div>
      <form className="w-full max-w-xl mx-auto">
        <div className="grid grid-cols-2 gap-x-6 gap-y-4">
          {/* Labels and Inputs */}
          <label className="text-right pt-2 font-medium">Position/Role</label>
          <input
            className="border w-full h-12 px-3 rounded"
            type="text"
            placeholder="Name of position / role"
            value={position}
            onChange={e => setPosition(e.target.value)}
          />
          <label className="text-right pt-2 font-medium">Experience</label>
          <input
            className="border w-full h-12 px-3 rounded"
            type="text"
            placeholder="Required Experience"
            value={experience}
            onChange={e => setExperience(e.target.value)}
          />
          <label className="text-right pt-2 font-medium">Skills Required</label>
          <input
            className="border w-full h-12 px-3 rounded"
            type="text"
            placeholder="Mention skills required"
            value={skills}
            onChange={e => setSkills(e.target.value)}
          />
          <label className="text-right pt-2 font-medium">Job description</label>
          <textarea
            className="border w-full h-12 px-3 rounded resize-none"
            placeholder="Write job description ..."
            value={description}
            onChange={e => setDescription(e.target.value)}
            rows={2}
          />
        </div>

        {/* OR and AI JD */}
        <div className="flex justify-center items-center mt-8 mb-2 gap-4">
          <span className="text-center">OR</span>
          <button
            type="button"
            className="border rounded px-4 py-2 font-semibold hover:bg-black hover:text-white transition"
            onClick={handleGenerateJD}
          >
            Generate JD
          </button>
          <div className="border rounded w-96 h-16 flex flex-col justify-center items-start px-4">
            <span className="text-sm text-gray-400">AI Generated Job Description</span>
            {aiDescription && (
              <div className="text-gray-700 text-sm mt-1">{aiDescription}</div>
            )}
            <div className="mt-1 text-sm text-gray-700">
              <a href="#" className="underline mr-4">Download JD</a>|
              <a href="#" className="underline ml-4">Edit &rarr;</a>
            </div>
          </div>
        </div>

        {/* Post Job Button */}
        <div className="flex justify-center mt-8">
          <button
            type="submit"
            className="border rounded px-10 py-3 font-medium text-lg hover:bg-black hover:text-white transition"
          >
            Post Job
          </button>
        </div>
      </form>
    </div>
    </>
  );
};

export default AddJobForm;
